### ISSUE TITLE
Translations Missing on Live Server

### ISSUE THREAD

**Issue by igerslike** [statikbe/laravel-chained-translator#1]
Once again thanks for the package. Seems like there is a little bug i couldnt figure out yet why but i can provide details of your live server if you need ( via PM )

Once "Saved" a specific translation the Laravel Nova Translation manager will only "show" the keys available at "lang-user" folder/file, not being aware of the "original" key/value located in lang folder. Im not sure if this a problem with this package ( but it seems so ) or in the Nova Package, but i cant seem to reproduce this issue on Local. At the same time, if i add the key on the lang-user folder it will show correctly but still not being aware of the of the fallback to lang folder correspondent.

I have temporary forked this repo and made a "hacky" solution that is load all the current base translations and merge them with the edited ones, as well introduced the package https://github.com/brick/varexporter for a cleaner export.

Packages/Enviorement : 

"laravel/framework": "^8.12",
"laravel/nova": "~3.0"

MYSQL 8.0
PHP 7.4
Provisioned by Laravel Forge

On Live Environment:

![image](https://user-images.githubusercontent.com/12662462/107379764-270ab400-6ae5-11eb-8bf2-d333f869dad5.png)

On Local Environment:

![image](https://user-images.githubusercontent.com/12662462/107379871-430e5580-6ae5-11eb-80cb-ba5007a7d800.png)

Translations Structure Example : 

![image](https://user-images.githubusercontent.com/12662462/107380105-7bae2f00-6ae5-11eb-8c12-ad4f2a5a48a8.png)

If more information needed let me know.

**Comment by sten** [comment]
@igerslike & @dllobell I have merged the pull request manually. It is available in v1.3.0 and v1.4.0 of the Nova tool.
Thanks a lot for your work @dllobell
