### ISSUE TITLE
JSON locales support

### ISSUE THREAD

**Issue by ExsyDev** [statikbe/laravel-chained-translator#3]
Hello. We have a translation with default laravel function:

`{{ __('Locale') }}`

I can translate this string in en.json in folder `resources/lang/en.json`. How I can write json translations with this package?

**Comment by sten** [comment]
@ExsyDev Currently, JSON is not supported. We would welcome a pull request. There are already several points prepared in the code where you can add this.

**Comment by Kobo-one** [comment]
Json support is now added in v2.1.0
