### ISSUE TITLE
Upgrade to Filament 3

### ISSUE THREAD

**Issue by alexandersix** [statikbe/laravel-chained-translator#7]
Hi! Love this plugin--been using it for a client where easy access to translations is important and they have had nothing but great things to say about it. Thanks for the awesome work!

I was curious if there were any current plans to update this plugin to work with Filament 3. It's currently not listed on the new Filament website's plugin page, so I assume that means that it hasn't been upgraded and verified for v3 yet.

If there are plans for an update to Filament 3, but you don't have the time, I'm happy to take a stab at it--just didn't want to be submitting PRs for something that's already in the works.

**Comment by sten** [comment]
Hi @alexandersix! Thanks for the nice words!

I am currently about the leave for holidays so this was on my agenda for early September. However if you can make a pull request, things can move forward much faster. Please use the repo of the filament plugin: https://github.com/statikbe/laravel-filament-chained-translation-manager 

This is the base package with the common logic, which will most likely not need an update.
